import { OrdemServico, OrçamentoItem, ItemEstoque, AgendamentoInstalacao, TransacaoFinanceira, PresetEstilo } from '../types';
import { seedParaGenes } from './proceduralSvg';

export const INITIAL_PRESETS: PresetEstilo[] = [
  {
    id: 'preset-01',
    nome: 'Portão Industrial Ripado Minimal',
    tipo: 'portao',
    genes: {
      angulo: 0,
      amplitude: 0,
      frequencia: 1,
      espessura: 3.5,
      espacamento: 7,
      assimetria: 0,
      temMoldura: true,
      estiloMoldura: 'industrial',
      familia: 'reto'
    },
    corHex: '#16181d',
    corNome: 'Preto Fosco Nobre',
    dataCriacao: '2026-09-20',
    descricao: 'Barras verticais retas com espaçamento denso e requadro tubular reforçado.'
  },
  {
    id: 'preset-02',
    nome: 'Grade Losango Treliça Corten',
    tipo: 'grade',
    genes: {
      angulo: 45,
      amplitude: 15,
      frequencia: 3,
      espessura: 2.2,
      espacamento: 14,
      assimetria: 0.1,
      familia: 'geometrico'
    },
    corHex: '#8c4323',
    corNome: 'Aço Corten Industrial',
    dataCriacao: '2026-09-22',
    descricao: 'Padrão geométrico estrutural em losangos para fachadas modernas.'
  },
  {
    id: 'preset-03',
    nome: 'Guarda-corpo Curva Senoidal Duna',
    tipo: 'guarda-corpo',
    genes: {
      angulo: 0,
      amplitude: 22,
      frequencia: 4,
      espessura: 2.0,
      espacamento: 10,
      assimetria: -0.15,
      alturaMinimaSeguranca: 110,
      familia: 'ondulado'
    },
    corHex: '#374151',
    corNome: 'Grafite Acetinado (RAL 7016)',
    dataCriacao: '2026-09-23',
    descricao: 'Ondulação suave orgânica em conformidade estrita com a NBR 14718.'
  },
  {
    id: 'preset-04',
    nome: 'Corrimão Dinâmico Escada 35°',
    tipo: 'corrimao',
    genes: {
      angulo: 35,
      amplitude: 0,
      frequencia: 1,
      espessura: 2.8,
      espacamento: 12,
      assimetria: 0,
      inclinacaoEscada: 35,
      familia: 'reto'
    },
    corHex: '#785b3b',
    corNome: 'Bronze Forja Champanhe',
    dataCriacao: '2026-09-24',
    descricao: 'Inclinação de rampa/escada com empunhadura ergonômica NBR 9050.'
  }
];

export const INITIAL_ORCAMENTOS: OrçamentoItem[] = [
  {
    id: 'orc-01',
    clienteNome: 'Mariana Drummond',
    clienteTelefone: '(11) 98722-4411',
    clienteEmail: 'mariana.drummond@arquitetura.com.br',
    endereco: 'Rua das Camélias, 420 - Alphaville, Barueri - SP',
    tipo: 'portao',
    descricao: 'Portão Pivotante Luxo 3.20m x 2.40m com Tubos Industriais e Puxador Embutido',
    dimensoes: { largura: 320, altura: 240 },
    genes: seedParaGenes(1420, 'portao'),
    corHex: '#16181d',
    corNome: 'Preto Fosco Nobre',
    valor: 8450.00,
    custoPrevisto: 3980.00,
    dataCriacao: '2026-09-21',
    validadeDias: 15,
    status: 'pendente',
    diasSemResposta: 3, // ALERTA: reforçar contato
  },
  {
    id: 'orc-02',
    clienteNome: 'Dr. Roberto Vasconcelos',
    clienteTelefone: '(11) 99182-3300',
    clienteEmail: 'r.vasconcelos@clinica.med.br',
    endereco: 'Av. Brigadeiro Faria Lima, 2900 - Itaim Bibi, São Paulo - SP',
    tipo: 'guarda-corpo',
    descricao: 'Guarda-corpo NBR 14718 em Aço Corten com Montantes de Segurança Reforçados',
    dimensoes: { largura: 580, altura: 110 },
    genes: seedParaGenes(3981, 'guarda-corpo'),
    corHex: '#8c4323',
    corNome: 'Aço Corten Industrial',
    valor: 14200.00,
    custoPrevisto: 6850.00,
    dataCriacao: '2026-09-23',
    validadeDias: 10,
    status: 'aprovado',
    diasSemResposta: 0,
    dataAprovacao: '2026-09-24',
    assinaturaDigital: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M10 40 Q 50 10 90 35 T 180 20" fill="none" stroke="%23f97316" stroke-width="2"/></svg>'
  },
  {
    id: 'orc-03',
    clienteNome: 'Eng. Felipe Siqueira',
    clienteTelefone: '(11) 97321-9988',
    clienteEmail: 'felipe@siqueiraconstrutora.com.br',
    endereco: 'Alameda dos Jacarandás, 88 - Alto de Pinheiros, SP',
    tipo: 'corrimao',
    descricao: 'Corrimão Contínuo com Tubo de Empunhadura Ergonômico e Ângulo 32°',
    dimensoes: { largura: 420, altura: 95 },
    genes: seedParaGenes(8820, 'corrimao'),
    corHex: '#374151',
    corNome: 'Grafite Acetinado (RAL 7016)',
    valor: 6890.00,
    custoPrevisto: 3120.00,
    dataCriacao: '2026-09-18',
    validadeDias: 15,
    status: 'pendente',
    diasSemResposta: 6, // ALERTA: Cliente não respondeu há 6 dias!
  },
  {
    id: 'orc-04',
    clienteNome: 'Carla Albuquerque',
    clienteTelefone: '(11) 98455-1221',
    clienteEmail: 'carla.albuquerque@design.com',
    endereco: 'Rua Bela Cintra, 1750 - Consolação, São Paulo - SP',
    tipo: 'grade',
    descricao: 'Grade de Proteção Estilo Veneziana Treliçada para Janelas de Fachada',
    dimensoes: { largura: 220, altura: 160 },
    genes: seedParaGenes(5120, 'grade'),
    corHex: '#785b3b',
    corNome: 'Bronze Forja Champanhe',
    valor: 4350.00,
    custoPrevisto: 1980.00,
    dataCriacao: '2026-09-22',
    validadeDias: 15,
    status: 'aprovado',
    diasSemResposta: 0,
    dataAprovacao: '2026-09-23',
    assinaturaDigital: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M20 30 Q 70 50 120 20 T 170 40" fill="none" stroke="%2322c55e" stroke-width="2"/></svg>'
  }
];

export const INITIAL_ORDENS_SERVICO: OrdemServico[] = [
  {
    id: 'os-101',
    numeroOS: 'OS-2026-081',
    clienteNome: 'Mariana Drummond',
    clienteTelefone: '(11) 98722-4411',
    clienteEndereco: 'Rua das Camélias, 420 - Alphaville',
    tipo: 'portao',
    titulo: 'Portão Pivotante Luxo 3.20m x 2.40m',
    dimensoes: { largura: 320, altura: 240 },
    genes: seedParaGenes(1420, 'portao'),
    corHex: '#16181d',
    corNome: 'Preto Fosco Nobre',
    perfilMaterial: 'Metalon 50x30x1.50mm + Barras 20x20',
    status: 'soldando',
    dataCriacao: '2026-09-20',
    dataPrometida: '2026-09-28',
    prazoApertado: true, // Alerta: faltam 4 dias
    valorTotal: 8450.00,
    valorEntrada: 4225.00,
    valorRestante: 4225.00,
    custoReal: 3740.00,
    responsavelCorte: 'Carlos Mendes',
    responsavelSolda: 'Valter Silva (MIG)',
    responsavelPintura: 'Marcos Epóxi',
    checklist: [
      { id: 'ck-1', descricao: 'Corte das barras de requadro 50x30 a 45° com precisão', concluido: true, responsavel: 'Carlos' },
      { id: 'ck-2', descricao: 'Desbaste de rebarbas e alinhamento do esquadro na bancada', concluido: true, responsavel: 'Carlos' },
      { id: 'ck-3', descricao: 'Ponteamento das travessas com gabarito de espaçamento', concluido: true, responsavel: 'Valter' },
      { id: 'ck-4', descricao: 'Cordão de solda MIG contínuo e estanque nos vértices', concluido: false, responsavel: 'Valter' },
      { id: 'ck-5', descricao: 'Lixamento técnico com disco flap grão 80 e limpeza', concluido: false, responsavel: 'Marcos' },
      { id: 'ck-6', descricao: 'Aplicação de fundo wash-primer anticorrosivo', concluido: false, responsavel: 'Marcos' },
      { id: 'ck-7', descricao: 'Pintura eletrostática poliéster cura 200°C', concluido: false, responsavel: 'Marcos' },
    ],
    observacoes: 'Cliente solicitou reforço extra para motor pivotante Peccinin de 1/2 HP.',
    retrabalhoHoras: 0,
    fotosAntesDepois: {
      antes: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=400&q=80',
    }
  },
  {
    id: 'os-102',
    numeroOS: 'OS-2026-082',
    clienteNome: 'Dr. Roberto Vasconcelos',
    clienteTelefone: '(11) 99182-3300',
    clienteEndereco: 'Av. Faria Lima, 2900 - Itaim Bibi',
    tipo: 'guarda-corpo',
    titulo: 'Guarda-corpo 5.80m x 1.10m NBR 14718',
    dimensoes: { largura: 580, altura: 110 },
    genes: seedParaGenes(3981, 'guarda-corpo'),
    corHex: '#8c4323',
    corNome: 'Aço Corten Industrial',
    perfilMaterial: 'Tubo Estrutural 40x40 + Chapa Corten 2mm',
    status: 'pintando',
    dataCriacao: '2026-09-18',
    dataPrometida: '2026-09-26',
    prazoApertado: true,
    valorTotal: 14200.00,
    valorEntrada: 7100.00,
    valorRestante: 7100.00,
    custoReal: 6420.00,
    responsavelCorte: 'Carlos Mendes',
    responsavelSolda: 'Valter Silva (MIG)',
    responsavelPintura: 'Marcos Epóxi',
    checklist: [
      { id: 'ck-1', descricao: 'Corte preciso dos 7 montantes verticais com tolerância ±1mm', concluido: true },
      { id: 'ck-2', descricao: 'Furação das sapatas para parabolts de ancoragem química', concluido: true },
      { id: 'ck-3', descricao: 'Solda TIG das conexões de topo para acabamento invisível', concluido: true },
      { id: 'ck-4', descricao: 'Aceleração do envelhecimento e óxido controlado Corten', concluido: true },
      { id: 'ck-5', descricao: 'Aplicação de resina protetora hidro-repelente fosca', concluido: false },
    ],
    observacoes: 'Instalação agendada para sábado de manhã com 2 ajudantes.',
    retrabalhoHoras: 1.5,
    retrabalhoMotivo: 'Ajuste de 5mm na sapata esquerda devido a desvio de alvenaria na obra.',
  },
  {
    id: 'os-103',
    numeroOS: 'OS-2026-083',
    clienteNome: 'Carla Albuquerque',
    clienteTelefone: '(11) 98455-1221',
    clienteEndereco: 'Rua Bela Cintra, 1750',
    tipo: 'grade',
    titulo: 'Grade de Janela Treliça Bronze 2.20m',
    dimensoes: { largura: 220, altura: 160 },
    genes: seedParaGenes(5120, 'grade'),
    corHex: '#785b3b',
    corNome: 'Bronze Forja Champanhe',
    perfilMaterial: 'Barra Chata 1" x 3/16" + Cantoneira 1"',
    status: 'cortando',
    dataCriacao: '2026-09-23',
    dataPrometida: '2026-10-02',
    prazoApertado: false,
    valorTotal: 4350.00,
    valorEntrada: 2175.00,
    valorRestante: 2175.00,
    custoReal: 1850.00,
    responsavelCorte: 'Carlos Mendes',
    responsavelSolda: 'Valter Silva (MIG)',
    responsavelPintura: 'Marcos Epóxi',
    checklist: [
      { id: 'ck-1', descricao: 'Corte das 36 barras diagonais na serra fita com ângulo 45°', concluido: true },
      { id: 'ck-2', descricao: 'Gabaritagem na mesa de corte', concluido: false },
      { id: 'ck-3', descricao: 'Soldagem cruzada com ponto de alívio térmico', concluido: false },
    ],
    observacoes: 'Grade com 4 garras de embutir na alvenaria.',
  },
  {
    id: 'os-104',
    numeroOS: 'OS-2026-079',
    clienteNome: 'Condomínio Spazio Di Verona',
    clienteTelefone: '(11) 3214-5500',
    clienteEndereco: 'Rua Pamplona, 930 - Jardim Paulista',
    tipo: 'corrimao',
    titulo: 'Corrimão de Acessibilidade 12 metros Rampa NBR 9050',
    dimensoes: { largura: 600, altura: 92 },
    genes: seedParaGenes(7733, 'corrimao'),
    corHex: '#16181d',
    corNome: 'Preto Fosco Nobre',
    perfilMaterial: 'Tubo Redondo 1.1/2" parede 2.00mm',
    status: 'pronto',
    dataCriacao: '2026-09-12',
    dataPrometida: '2026-09-25',
    prazoApertado: false,
    valorTotal: 9600.00,
    valorEntrada: 4800.00,
    valorRestante: 4800.00,
    custoReal: 4100.00,
    responsavelCorte: 'Carlos Mendes',
    responsavelSolda: 'Valter Silva (MIG)',
    responsavelPintura: 'Marcos Epóxi',
    checklist: [
      { id: 'ck-1', descricao: 'Conformação e calandragem das curvas nas pontas', concluido: true },
      { id: 'ck-2', descricao: 'Solda e acabamento espelhado nas emendas', concluido: true },
      { id: 'ck-3', descricao: 'Pintura eletrostática final inspecionada', concluido: true },
    ],
    observacoes: 'Peça embalada com plástico bolha e pronta no cavalete de expedição.',
  }
];

export const INITIAL_ESTOQUE: ItemEstoque[] = [
  {
    id: 'est-01',
    codigo: 'MT-5030-15',
    nome: 'Metalon 50x30 Chapa 16 (1.50mm) Barra 6m',
    categoria: 'metalon',
    unidade: 'barra_6m',
    quantidadeAtual: 14,
    estoqueMinimo: 20, // ALERTA: Estoque Baixo!
    custoUnitario: 89.50,
    fornecedorPrincipal: 'Gerdau Comercial / Açotécnica SP',
    prazoEntregaDias: 2
  },
  {
    id: 'est-02',
    codigo: 'MT-3020-12',
    nome: 'Metalon 30x20 Chapa 18 (1.20mm) Barra 6m',
    categoria: 'metalon',
    unidade: 'barra_6m',
    quantidadeAtual: 38,
    estoqueMinimo: 25,
    custoUnitario: 52.00,
    fornecedorPrincipal: 'Distribuidora Central do Aço',
    prazoEntregaDias: 1
  },
  {
    id: 'est-03',
    codigo: 'MT-2020-12',
    nome: 'Metalon 20x20 Chapa 18 (1.20mm) Barra 6m',
    categoria: 'metalon',
    unidade: 'barra_6m',
    quantidadeAtual: 8,
    estoqueMinimo: 15, // ALERTA: Estoque Baixo!
    custoUnitario: 38.00,
    fornecedorPrincipal: 'Distribuidora Central do Aço',
    prazoEntregaDias: 1
  },
  {
    id: 'est-04',
    codigo: 'BC-100-316',
    nome: 'Barra Chata 1" x 3/16" Barra 6m',
    categoria: 'barra',
    unidade: 'barra_6m',
    quantidadeAtual: 22,
    estoqueMinimo: 10,
    custoUnitario: 44.00,
    fornecedorPrincipal: 'Gerdau Comercial',
    prazoEntregaDias: 3
  },
  {
    id: 'est-05',
    codigo: 'CT-114-18',
    nome: 'Cantoneira Abas Iguais 1.1/4" x 1/8" Barra 6m',
    categoria: 'cantoneira',
    unidade: 'barra_6m',
    quantidadeAtual: 19,
    estoqueMinimo: 12,
    custoUnitario: 58.00,
    fornecedorPrincipal: 'Açotécnica SP',
    prazoEntregaDias: 2
  },
  {
    id: 'est-06',
    codigo: 'EL-6013-25',
    nome: 'Eletrodo Revestido AWS E6013 2.5mm Caixa 5kg',
    categoria: 'consumivel',
    unidade: 'unidade',
    quantidadeAtual: 3,
    estoqueMinimo: 5, // ALERTA: Estoque Baixo!
    custoUnitario: 78.00,
    fornecedorPrincipal: 'Oxigênio & Soldas Brasil',
    prazoEntregaDias: 1
  },
  {
    id: 'est-07',
    codigo: 'DC-45-INX',
    nome: 'Disco de Corte Fino 4.1/2" x 1.0mm para Inox/Aço',
    categoria: 'consumivel',
    unidade: 'unidade',
    quantidadeAtual: 42,
    estoqueMinimo: 30,
    custoUnitario: 4.20,
    fornecedorPrincipal: 'Oxigênio & Soldas Brasil',
    prazoEntregaDias: 1
  },
  {
    id: 'est-08',
    codigo: 'TI-EPOXI-PF',
    nome: 'Tinta Eletrostática a Pó Poliéster Preto Fosco Nobre 25kg',
    categoria: 'consumivel',
    unidade: 'kg',
    quantidadeAtual: 35,
    estoqueMinimo: 20,
    custoUnitario: 34.00,
    fornecedorPrincipal: 'Tintas Farben Industrial',
    prazoEntregaDias: 3
  }
];

export const INITIAL_INSTALACOES: AgendamentoInstalacao[] = [
  {
    id: 'inst-01',
    osId: 'os-104',
    clienteNome: 'Condomínio Spazio Di Verona',
    endereco: 'Rua Pamplona, 930 - Jardim Paulista, São Paulo',
    bairro: 'Jardim Paulista',
    data: '2026-09-25',
    horario: '08:30',
    equipe: ['Carlos Mendes (Mestre)', 'Lucas Ajudante'],
    status: 'agendado',
    checklist: {
      medicaoConferida: true,
      nivelamentoPrumo: false,
      fixacaoChumbadores: false,
      lubrificacaoRoldanas: false,
      retoquePintura: false,
      limpezaGeral: false
    }
  },
  {
    id: 'inst-02',
    osId: 'os-102',
    clienteNome: 'Dr. Roberto Vasconcelos',
    endereco: 'Av. Brigadeiro Faria Lima, 2900 - Cobertura',
    bairro: 'Itaim Bibi',
    data: '2026-09-27',
    horario: '09:00',
    equipe: ['Valter Silva', 'Lucas Ajudante'],
    status: 'agendado',
    checklist: {
      medicaoConferida: true,
      nivelamentoPrumo: false,
      fixacaoChumbadores: false,
      lubrificacaoRoldanas: false,
      retoquePintura: false,
      limpezaGeral: false
    }
  }
];

export const INITIAL_TRANSACOES: TransacaoFinanceira[] = [
  {
    id: 'tr-01',
    data: '2026-09-24',
    descricao: 'Sinal 50% OS-2026-082 (Guarda-corpo Dr. Roberto)',
    tipo: 'entrada',
    categoria: 'venda_os',
    valor: 7100.00,
    status: 'pago',
    vencimento: '2026-09-24',
    osIdRelacionada: 'os-102'
  },
  {
    id: 'tr-02',
    data: '2026-09-23',
    descricao: 'Compra de 25 barras Metalon 50x30 Gerdau',
    tipo: 'saida',
    categoria: 'compra_aco',
    valor: 2237.50,
    status: 'pago',
    vencimento: '2026-09-23'
  },
  {
    id: 'tr-03',
    data: '2026-09-21',
    descricao: 'Sinal 50% OS-2026-081 (Portão Mariana Drummond)',
    tipo: 'entrada',
    categoria: 'venda_os',
    valor: 4225.00,
    status: 'pago',
    vencimento: '2026-09-21',
    osIdRelacionada: 'os-101'
  },
  {
    id: 'tr-04',
    data: '2026-09-20',
    descricao: 'Consumíveis Oxigênio & Soldas (Eletrodos + Discos)',
    tipo: 'saida',
    categoria: 'consumiveis',
    valor: 640.00,
    status: 'pago',
    vencimento: '2026-09-20'
  },
  {
    id: 'tr-05',
    data: '2026-09-28',
    descricao: 'Saldo Restante 50% OS-2026-081 na Entrega',
    tipo: 'entrada',
    categoria: 'venda_os',
    valor: 4225.00,
    status: 'pendente',
    vencimento: '2026-09-28',
    osIdRelacionada: 'os-101'
  }
];
